# ETAPA 1: Compilación (SDK)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/EventReservations/EventReservations.csproj", "EventReservations/"]

RUN dotnet restore "EventReservations/EventReservations.csproj"

# 3. Copiam todo el contenido de la raíz (incluyendo src y test)
COPY . .

WORKDIR "/src/src/EventReservations"
RUN dotnet build "EventReservations.csproj" -c Release -o /app/build

# ETAPA 2: Publicación
FROM build AS publish
RUN dotnet publish "EventReservations.csproj" -c Release -o /app/publish /p:UseAppHost=false

# ETAPA 3: Imagen Final (Runtime)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000

ENTRYPOINT ["dotnet", "EventReservations.dll"]